### ISSUE TITLE
Extents not updating within KnownExtentsListView after parent widget providing extents are changed

### ISSUE THREAD

**Issue by mitchhymel** [bendelonlee/known_extents_list_view_builder#5]
Let me start off by saying that I'm not sure if my problem is from my incorrect usage of KnownExtentsListView or if it is indicating a bug within KnownExtentsListView.

From what I'm seeing, it looks like KnownExtentsListView does not update its internal extents when its parent widget updates it with new extents. 

My scenario is that I have a large list (100k+) of items/widgets, each with dynamic (but known) heights, and I want to be able to apply filters to the list to show/hide certain items, which means I am changing the items and extents I'm passing into KnownExtentsListView.

Here is a minimal widget that will show the issue I'm trying to describe, you can see that when the extents are reversed, the widgets react appropriately to the height change, but KnownExtentsListView is still using the initial extents (e.g. the first item starts with height of 40 and extent of 40, then when reversed the first item has a height of 120 but still only given an extent of 40 in KnownExtentsListView):
```dart
import 'package:flutter/material.dart';
import 'package:known_extents_list_view_builder/known_extents_list_view_builder.dart';

class ListTestScreen extends StatefulWidget {
  @override
  State createState() => _ListTestScreenState();
}

class _ListTestScreenState extends State<ListTestScreen> {

  late List<double> extents;

  @override
  void initState() {
    super.initState();

    extents = List.generate(10000, (index) {
      return 20*(2+index%5);
    });
  }

  getColorForIndex(index) {
    switch (index%5) {
      case 0:
        return Colors.yellow;
      case 1:
        return Colors.orangeAccent;
      case 2:
        return Colors.blue;
      case 3:
        return Colors.red;
      case 4:
        return Colors.purple;
      default:
        return Colors.green;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          child: const Text('Reverse'),
          onPressed: () {
            setState(() {
              extents = extents.reversed.toList();
            });
          },
        ),
        Expanded(
          child: KnownExtentsListView.builder(
            itemExtents: extents,
            itemBuilder: (_, index) {
              return Container(
                height: extents[index],
                margin: const EdgeInsets.all(8.0),
                decoration: BoxDecoration(
                  border: Border.all(
                    width: extents[index]/20,
                    color: getColorForIndex(index),
                  )
                ),
                child: Text('index $index with extent ${extents[index]}')
              );
            },
          )
        )
      ],
    );
  }
}
```

**Comment by bendelonlee** [comment]
Handling changing extents is something I built into the Reorderable version, but not the plain one. 

You can force Flutter to rebuild by passing in a key that changes when extents change. For example: 

```dart
KnownExtentsListView.builder(
          key: ValueKey(extents.hashCode),
          itemExtents: extents,
          ....
```

This has a possibly undesired side effect of reseting the scroll offset to 0. There's ways around this by keeping a scrollController in state, but it's not the most simple solution.

I'll look into maybe fixing this inside the package. 
Let me know how it goes for you. :)

**Comment by bendelonlee** [comment]
This is very easy to fix inside the package, and I put up a PR to do it:

https://github.com/bendelonlee/known_extents_list_view_builder/compare/extentsChangeInPlainListFix?expand=1

This would keep the scrollOffset the same instead resetting it back to 0. Is this useful to you? It would still be another step to keep the same index in view.

As a sidebar, if don't need the list to be reorderable, you may find it easier to use [scrollable positioned list](https://pub.dev/packages/scrollable_positioned_list) which keeps track of elements by index and not scroll offset.

I'm about to run off but let me if you'd use this and I'll merge it by the end of the weekend

**Comment by mitchhymel** [comment]
The suggestion of using the key gives me the behavior I want, and I don't mind that the scroll offset resets to 0. Thanks for the quick response!
